services:
  postgres:
    image: postgres:16-alpine
    container_name: wms-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wms_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d wms_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: .
    container_name: wms-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/wms_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: